# Generated by Django 3.2 on 2022-07-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Категория-видео',
                'verbose_name_plural': 'Категории-видео',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='videoService.categoryvideo', verbose_name='категория'),
        ),
    ]
