# Generated by Django 3.2 on 2022-07-30 14:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0002_auto_20220712_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_items', to='videoService.categoryvideo', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app/media'), upload_to='video/%Y/%m/%d/', verbose_name='видео'),
        ),
    ]
