# Generated by Django 3.2 on 2022-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0003_auto_20220730_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='заставка'),
        ),
        migrations.AddField(
            model_name='video',
            name='raiting_kino',
            field=models.FloatField(blank=True, null=True, verbose_name='рейтинг кинопоиск'),
        ),
    ]
