# Generated by Django 3.2 on 2022-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0004_auto_20220730_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age',
            field=models.FloatField(blank=True, null=True, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='video',
            name='coast_min',
            field=models.FloatField(blank=True, null=True, verbose_name='кол-во минут'),
        ),
        migrations.AddField(
            model_name='video',
            name='raiting_imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='рейтинг IMDb'),
        ),
        migrations.AddField(
            model_name='video',
            name='year_prod',
            field=models.FloatField(blank=True, null=True, verbose_name='год производства'),
        ),
    ]
