# Generated by Django 3.2 on 2022-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0005_auto_20220730_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryvideo',
            name='component',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='тип банера (1 - 2 - 3)'),
        ),
    ]
