# Generated by Django 3.2 on 2022-07-30 15:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0006_categoryvideo_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media'), upload_to='video/%Y/%m/%d/', verbose_name='видео'),
        ),
    ]
