# Generated by Django 3.2 on 2022-07-22 13:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogService', '0003_auto_20220717_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media'), upload_to='photos'),
        ),
    ]
