# Generated by Django 3.2 on 2022-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogService', '0004_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
