version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn mainApp.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./datadb2:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db