version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn mainApp.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
  db:
    env_file:
      - ./.env.prod.db