---
- name: Loops Playbook
  hosts: staging_servers
  become: yes

  tasks: 
  - name: Say hello to All
    debug: msg="Hello {{ item }}"
    loop:
      - "MIA"
      - "JAK"
      - "Patya"
  
  - name: Touch file
    file: "path=/myfile.txt state=absent"
  
  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print output
    debug:
      var: output.stdout

  - name: Install Package
    apt: name={{ item }} state=latest
    with_items:
      - python
      - tree
      - vim
      - make
      - cmatrix
      # - docker