# This is a basic workflow to help you get started with Actions

name: CI-githubActioons
env:
  aplicationName: "My_django"
  packageName: "Solanka"
  varsionName: "poltoraMinora"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: git clone my repo
        uses: actions/checkout@v1
        env:
          var1: "this is varioale"
          var2: "This is variable two"
    
      - name: Print in testing
        run: ls -la
      
      - name: Print env variables
        env:
          LOCAL_VAR: "Super-Local"
        run: |
          echo "${{ env.var1 }} - ${{ env.var2 }}"
          echo "var3 -- $LOCAL_VAR"
        
      - name: Print avalible AWS
        run: aws --version
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: command avalible Gzip
        run: gzip --version
        
      - name: Print version project
        run: echo "Deploy package is ${{ env.packageName }}"
  
