# This is a basic workflow to help you get started with Actions

name: CI-githubActioons
env:
  aplicationName: "My_django"
  packageName: "Solanka"
  varsionName: "poltoraMinora - ${{ github.sha }}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print in testing
      - run: echo 'Helloy-world!!) - '
        
      - name: Print for execute commands
      - run: |
          echo "Hello message one"
          echo "Hello message two"
          echo "Application name: ${{ env.aplicationName }}"
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: Print2
      - run: echo 'Hello world from deploy'
        
      - name: Print version project
      - run: |
          echo "Deploy package is ${{ env.packageName }} - ${{ env.varsionName }}"
  
