# This is a basic workflow to help you get started with Actions

name: CI-githubActioons
env:
  aplicationName: "My_django"
  packageName: "Solanka"
  varsionName: "poltoraMinora"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: git clone my repo
        uses: actions/checkout@v1
    
      - name: Print in testing
        run: ls -la
        
      - name: Print avalible AWS
        run: aws --version
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: command avalible Gzip
        run: gzip --version
        
      - name: Print version project
        run: echo "Deploy package is ${{ env.packageName }}"
  
